### ISSUE TITLE
Separate download from link creation (was: Error launching danker.sh)

### ISSUE THREAD

**Issue by AlessandroCalio** [athalhammer/danker#11]
Hi, I'm interested in your project but I have this error.

I'm using Debian 10, I have created a venv and installed the packages necessary for running your project.
What i'm doing wrong?
Thanks in advance

![image](https://user-images.githubusercontent.com/61049485/77282525-775d0580-6cca-11ea-90d3-c08dcf07b2f9.png)

**Comment by athalhammer** [comment]
Dear Alessandro,

It looks like you need to install the curl command (`sudo apt-get install curl`). I was assuming that it is available on most Linux systems.

Cheers
Andreas

**Comment by AlessandroCalio** [comment]
Thanks a lot, I'm not a very experienced linux user. I noticed that I was having dependency issues with the curl package and reinstalled it. Now is seems working :) . 

Sorry for the off topic but i also wanted to tell you that it would be very convenient to launch danker on user-chosen dumps.
Is it already possible?

**Comment by athalhammer** [comment]
You mean specifying a date in addition to the language edition (e.g., 2019-06-01)?

**Comment by AlessandroCalio** [comment]
Exactly, or give the possibility to input an already downloaded dump.

**Comment by athalhammer** [comment]
This has been implemented now and a folder as well as an alternative dumpdate can be specified. E.g. for an old english dump:

`./danker.sh en --project wiki --dump-date 20120101 --folder myfolder`
