### ISSUE TITLE
A Spider Web For Other Sites?

### ISSUE THREAD

**Issue by cheznewa** [athalhammer/danker#15]
Hello, Is Possible To Add A Crawler/Spider Web For Other Website For Generate Graph And Calcul PageRank?
Me I Never Found A Software That Generate Graph From A Website.

**Comment by athalhammer** [comment]
Hi, a web spider is clearly out of scope for danker. However, if you build one or use one of the shelf you can compute PageRank with danker on any graph. See https://github.com/athalhammer/danker/blob/master/README_PR.md.
