### ISSUE TITLE
Conserve The Titles At Output

### ISSUE THREAD

**Issue by cheznewa** [athalhammer/danker#16]
Hi/Hello, Is Possible To Conserve The Article Name, In Rank File, Because It's For Avoid To Get Name From Wikidata Website.

**Comment by athalhammer** [comment]
@cheznewa thanks for your feedback! This is something that was intentionally avoided in order to keep the memory and storage footprint low. Also, we compute PageRank on the merged graphs of multiple language editions: not all items that are contained in the output have an English label.
