### ISSUE TITLE
Updated dumps?

### ISSUE THREAD

**Issue by AliFlux** [athalhammer/danker#18]
Hi.

Is there a plan to publish an updated dump? The[ last available dump here ](https://danker.s3.amazonaws.com/index.html)is 2021-11-15.

Thanks.

**Comment by athalhammer** [comment]
Hi @AliFlux ,

Thanks for you question and also thanks for your patience. At the moment there are no new dumps planned. Any particular entities that you are missing?

**Comment by athalhammer** [comment]
closed due to inactivity

**Comment by athalhammer** [comment]
@AliFlux a new version is now online - if still of interest
