### ISSUE TITLE
Issue running danker on my machine

### ISSUE THREAD

**Issue by jgarcia1599** [athalhammer/danker#20]
Hello, I am interested in using danker on my machine (MacBook pro 2018,6-Core i7, 16gb ram) using the provided bash script, but I am encountering the following issue after doing the following steps:
 
1. Download the danker repository. 
2. Running the following bash script once I am inside the repo in the terminal: 
```
./danker.sh en
```
After completing the steps above, I encounter the following error: 

<img width="549" alt="Screenshot 2023-01-02 at 12 16 35 PM" src="https://user-images.githubusercontent.com/44903609/210266949-8b4168c2-3b36-4d01-8f02-8a2ffeec41f7.png">

Am I required to provide the date argument for danker to work?

**Comment by athalhammer** [comment]
Thanks a lot for your interest, @jgarcia1599! danker unfortunately doesn't have compatibility with macOS as many commands  used are slightly different in the Mac environment. Probably the easiest way to get this running on your hardware would be to run it in a docker container with an image based on Ubuntu or Debian. Could that be an option? Let me know if you need more concrete instructions on how to set this up and I'm happy to help.

**Comment by athalhammer** [comment]
closed due to inactivity
