### ISSUE TITLE
support for other wiki sites (wikipedia, wikisource, wikibooks ...)

### ISSUE THREAD

**Issue by chezsick** [athalhammer/danker#8]
hi/hello, is possible to add to access other wiki sites than wikipedia? like wikisource wikibooks wiktionary etc...

thanks to add, sick.

**Comment by athalhammer** [comment]
Hi @chezsick, could you explain the use case you have in mind? I think it should be possible but some modifications would be required.

**Comment by chezsick** [comment]
just to modify the argument language
current :: ./danker.sh LANG [BIGMEM]
request :: ./danker.sh LANG[SITE] [BIGMEM]

for example if i want wikinews ::: ./danker.sh ennews BIGMEM
and for all edition of wikinews ::: ./danker ALLnews

**Comment by athalhammer** [comment]
okay, working on it in branch feature/include-other-wiki-projects

**Comment by athalhammer** [comment]
Added experimental support for wikibooks, wikisource, wikiversity, and wikinews. To add further projects is straight-forward.
You can do now:
```
./danker.sh ALL -p books
./danker.sh en --project source
```

**Comment by chezsick** [comment]
Thank you very much!!!

**Comment by cheznewa** [comment]
and it possible add wiktionary project?

**Comment by athalhammer** [comment]
Let me look into this (it may take a while). I would also be curious about your concrete use case, if you want to share.

**Comment by athalhammer** [comment]
This is supported now, e.g. `./danker.sh ast --project wiktionary`
